Fixing the other mismatched type (introducing &&limit into the closure, why needed?), exposes new errors... Seems our return-a-reference wasn't so good after all :-)
12 times: (once for each test)
error[E0277]: the trait bound `{integer}: std::cmp::PartialEq<&u32>` is not satisfied
  --> tests/sum-of-multiples.rs:72:5
   |
72 |     assert_eq!(0, sum_of_multiples(10000, &vec![]))
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trait `{integer}: std::cmp::PartialEq<&u32>` not satisfied
   |